### ISSUE TITLE
Data type manipulation: permitted before initialisation of MPI and thread safety

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpiwg-sessions/sessions-issues#14]
None of the data type functionality is in the sessions namespace (no session handle parameter), so this is an orthogonal proposal.

Idea: allow the creation and manipulation of MPI data types independently of the rest of MPI; specifically, before MPI initialisation (by whatever method) and after MPI finalisation.

This requires all MPI data type functions to be thread-safe because there is no sure way to ascertain the applicable thread support level.

Use-cases include using MPI data types to describe data layouts for non-MPI scenarios, including as part of other programming systems or in non-MPI libraries/components.

**Comment by hppritcha** [comment]
closing for now.
