### ISSUE TITLE
Need to fix text moved from ei chapter after FT proposal concerning default error handler (#102)

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpiwg-sessions/sessions-issues#15]

**Comment by hppritcha** [comment]
related to https://github.com/mpi-forum/mpi-standard/pull/644 and https://github.com/mpi-forum/mpi-standard/pull/629

**Comment by hppritcha** [comment]
this was probably closed by changes in 4.1 text.

**Comment by hppritcha** [comment]
closed via https://github.com/mpi-forum/mpi-standard/pull/644
and
https://github.com/mpi-forum/mpi-standard/pull/629
