### ISSUE TITLE
feedback from 12/9/19 MPI forum plenary reading

### ISSUE THREAD

**Issue by hppritcha** [mpiwg-sessions/sessions-issues#20]
Only review changes from the September '19 MPI Forum.  
- [x] Ryan found a space problem with ```MPI_Session_init``` - but doesn't matter since we're switching to Python generated bindings
- [x] title in first example using ```communicator``` rather than ```Communicator```
- [x] how to build examples, talk with Bill G.
- [x]  more discussion of capitalization - Rolf says communicator not Communicator
- [x] don't capitalize session either for consistency
- [x] Rolf wants a change bar version pdf for the votes.  Could git latex diff help?
- [x] discussion of our fabulous empty set vs union of of the two process sets.
- [x] Ryan asks about the not changing the process set name after a call to ```MPI_Sessoin_get_nth_pset```
- [x] problem in changelog at B1.1 item 2.  Bad reference after 6.6.2
- [x] max string size issue  - Jeff says let Fortran be Fortran and C be C.    We've decided to punt on this problem since its beyond just being a sessions problem.  Maybe though follow pattern of ```MPI_MAX_OBJECT_NAME```.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
> fabulous empty set vs union

Resolution: no change.

> Ryan asks about the not changing the process set name

Resolution: no change.

> max string size issue - Jeff says

Resolution: no change.

> problem in changelog 

Resolution: fixed in PR #43

**Comment by hppritcha** [comment]
completed
