### ISSUE TITLE
more fixes for PR 55

### ISSUE THREAD

**Issue by hppritcha** [mpiwg-sessions/sessions-issues#3]
- [x] simplify first sessions example to be like ```library_init```
- [x] redo figure for sessions to not have wavy lines and to have correct 
- [x] review more places in standard with ```MPI_COMM_SELF``` and adjust as needed

And more todos from 12/5/18 Forum reading feedback:

- [x] Martin wants to drop “unless the application explicitly calls MPI_INIT” in page 416, lines 46-47.  Add valid as an adjective to MPI COMM WORLD in this section. 
- [x] We need to fix the second paragraph of 10.1 to better integrate the dynamic process model back into the 3 models for process creation
- [x] fix 10.1 subtitle!
- [x] page 417 line 22 add Window or File
- [x] water down line 45 on page 416 or remove
- [x] question about MPC-MPI  MPI process is a thread model from Aurelian and Martin.   We need to think about this – maybe add a blurb in the pset definition
- [x] Maybe move last paragraph in 10.4 up to intro part of chapter and reword a bit.  remove backward compatible?
- [x] swap 10.4.1 with 10.4.2.
- [x] page 418 line 1  remove use of “runtime” in that first, todo: decide if we want to mandate or highly recommend mpi://UNIVERSE and mpi://comm type shared.no examples.
- [x] make clearer what’s going on with lines 4-5, what exactly is a pset.  define semantically?    
- [x] key is mandatory for all process sets - Jeff Squyres thinks this needs more verbiage.
- [x] add some more discussion about the flags bit mask to MPI Session init.
- [x] fix f08 binding for MPI_Session_init flags should be TYPE(MPI_Flags), check other f08 bindings too where INTEGER should be replaced with a TYPE
- [x] could we use info arg to  MPI_Session_init rather than flags?
- [x] use tools cvar/pvar approach for psets and their lengths
- [x] replace MPI_Errhandler with MPI_Session_errhandler in multiple places (actually this is wrong)
- [x] add text for thread level support 
- [x] Aurelian asks about thread safety for things like data type manipulation, etc.  This needs to go with the info ops before MPI Init discussion.
<del>- [ ] an advice to users about sessions and how implementations may use them – Dan talks about isolation and multiplexing, grouping of communicators.  (decided this is a user manual item)</del>
- [x] should we call Sessions Enclaves, Instances?  
- [x] pre-defined info keys
- [x] need to add local to the description of MPI_Session_init
- [x] be consistent with capitalization of session/enclave Martin says put MPI in front of Enclave or Session
- [x] function name for MPI_Session_init line 46 on page 418
- [x] make session handle in out to MPI_Session_finalize 
- [x]  need a lot more text for MPI_Session_finalize – use analogous not equivalent, should we add a drop-all-resources type of call that frees all resources associated with a session.  Collective.  Files, windows, communicators, groups get leaned up
- [x] MPI Session get num sets replace pset_name with npsets or something like this, same issue with get_psetlen  
<del> - [ ] could we replace all this with an in/out info object </del>
- [x] definitely need to keep the figure
- [x] rework chapter describing MPI_SESSION_GET_NTH_PSET about room for NULL terminator etc.  Check MPI T and info in the code example title add a reference to chapter six functions.
- [x] question about where the example would block 
- [x] verbiage about session finalize associated with the example
- [x] uniqueness of uri (Jeff says don’t use this!!!) across sets of processes, suggestion and advice to users for MPI_Create_comm_from_group gov://llnl thingy 
- [x] should we rename MPI_GROUP_FROM_SESSION_PSET .  maybe return MPI GROUP NULL  if not valid pset name?

More todos/feedback from 1/30/19 virtual forum:
- [x] unless you call MPI init MPI_COMM_WORLD is not valid (add to the world process model section of chapter 10)
- [x] an instead of a in several places
- [x] line 1101 in dynamic-2.tex INITIALIZE replace with INIT
- [x] scope of unique set name - Martin asks about this for process sets.  mpi://self problem.  disjoint and unique - maybe add a picture?  Dan gives example of MPI_COMM_SPLIT with each process providing a different key
<del>- [ ] MPI_SESSION_GET_NTH_PSET - may need something different for Fortran (check with Nathan).  Martin wonders if this will cause a problem for PMPI.   tool wanting to add its own process set, example of tool generating the PSET NAME.  maybe already add NULL terminator even for Fortran.</del>  
- [x] check for MPI_SESSION_GET_INFO for session type
- [x] add FORTRAN seesions example

**Comment by hppritcha** [comment]
notes from 2/25/19 webex:

more discussion of replacing the bit flags mask with info key/values.  Pretty convinced we can go with info and drop bit flags.  Leave as is for the reading week of 3/4.

functions callable before ```MPI_Init```, ```MPI_Session_init```, etc. is deferred to the work being done by FT wg.  ```MPI_Info_create``` and related accessors and destructors, in addition to MPI errorhandler constructors and destructors.

discussion of changing from session to something different.  Maybe take a vote at the 3/4 reading.

discuss ```uri``` arg to ```MPI_Comm_from_group```.  Need to find out from Jeff his objections to uri format.  We should probably say a little more about the uniqueness of ```uri```.

discuss ```MPI_Group_from_pset``` - different name?  also return MPI_GROUP_EMPTY if pset name is not valid.

Should double check the Fortran.

need to sync up with tools people about MPI_T and sessions.  Should have something done in time for June '19 forum.  maybe as errata for 4.0, or delay till 4.1?

**Comment by dholmes-epcc-ed-ac-uk** [comment]
All items ticked off - either completed or copied to another issue.
