### ISSUE TITLE
MPI_INFO_ENV  and sessions - may need clarification/testing in implementation

### ISSUE THREAD

**Issue by hppritcha** [mpiwg-sessions/sessions-issues#9]
We probably need to add verbiage about use of ```MPI_INFO_ENV``` pre-defined info object in the peer to peer model.  I'm in favor of saying this info object is available for use by the application after the first invocation of MPI_Session_init

**Comment by dholmes-epcc-ed-ac-uk** [comment]
The current text states (MPI-3.1, page 356, line 20): "After MPI is initialized"

If MPI_INFO_ENV is available after the first session init then it would also be available before MPI_Init, which is not currently (expressly) permitted.
```
MPI_Session_init();
/* query MPI_INFO_ENV */
MPI_Init();
```

Most of the key/value pairs seem innocuous except: if the value MPI uses for the argv key/value comes from the parameter passed in to MPI_Init, then the user may get a different answer from queries before and after MPI_Init.

**Comment by hppritcha** [comment]
Need to see if its possible to do this with the proto-type.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Item from a forum feedback issue:

Discussion of MPI_INFO_ENV - should this be usable if no active session - for now only allow in world model. Dan asks: can MPI_INFO_ENV be populated without access to argv? See issue:mpi-forum/mpi-issues#115 (PR mpi-forum/mpi-standard#110), which also punts on this change for the same reason.

**Comment by hppritcha** [comment]
closing this issue as the ```MPI_Info_create_env``` route was taken as a means for providing support for an info object similar  to ```MPI_INFO_ENV```   when only using the sessions process model.
